config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :path => '', :path_names => {:sign_in => 'getin', :sign_out => 'logout', :sign_up => 'ahlan_tars'}
  resources :articles

  get 'about'     => 'pages#about'
  get 'services'  => 'pages#services'
  get 'projects'  => 'pages#projects'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  has_many :articles

  before_save {self.email = email.downcase}

  validate :validate_username

  def validate_username
    if Admin.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

   def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_hash).first
      end
    end
end

app/models/article.rb
class Article < ActiveRecord::Base
  default_scope -> { order('created_at DESC') }

  # association
  belongs_to :admin

  # validation
  validates :headline,  presence: true, length: { within: 3..255 }
  validates :intro,     presence: true, length: { within: 5..1000 }
  validates :body,      presence: true, length: { maximum: 10000 }

  # FriendlyId
  extend FriendlyId
  friendly_id :headline, use: [:slugged, :history]
  def should_generate_new_friendly_id?
    headline_changed?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article,           only: [:edit, :update, :destroy]
  before_action :set_article_redirect,  only: [:show]
  before_action :authenticate_admin!, except: [:index, :show]

  include HighVoltage::StaticPage
  layout 'articles_layout'

  def index
    @articles = Article.all
  end

  def show
    render layout: 'show_article_layout'
  end

  def new
    @article = current_admin.articles.build
  end

  def edit
  end

  def create
    @article = current_admin.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:headline, :slug, :intro, :body, :admin_id)
    end

    def set_article_redirect
      @article = Article.friendly.find(params[:id])
      # If an old id or a numeric id was used to find the record, then
      # the request path will not match the article_path, and we should do
      # a 301 redirect that uses the current friendly id.
      if request.path != article_path(@article)
        redirect_to @article, status: :moved_permanently
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  include HighVoltage::StaticPage
  
  def home
  end

  def about
  end

  def services
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Ahmed Nadar"
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
  # how to use it
  # check [layouts/application.html.erb]

  def active_class(link_path)
    active = current_page?(link_path) ? "active" : "no-active"
  end
  #  active if params[:category] == category.name
  # how to use it
  # check [layouts/partials/_header.html.erb]

  def meta_author
    "Ahmed Nadar"
  end

  def meta_description
    "Ahmed Nadar, offers consultent for web development and design"
  end

  def meta_keywords
    "Web Development"
  end

  def site_url
    if Rails.env.production?
      # Place production URL
      "http://www.ahmednadar.com/"
    else
      # Our dev & test URL.
      "http://localhost:3000"
    end
  end

  class HTMLwithPygments < Redcarpet::Render::HTML
    include Redcarpet::Render::SmartyPants
    def block_code(code, language)
      Pygments.highlight(code, lexer: language, options: {lineanchors: "line"})
    end
  end

  # markdown format
  def markdown(text)
    Haml::Template.options[:ugly] = true
    renderer = HTMLwithPygments.new(prettify: true, hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      ugly: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_spacing: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
      highlight: true,
      quote: true,
      footnotes: true,
      tables: true
    }
    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_disqus.html.haml
#disqus_thread
:javascript

  /*
  var disqus_config = function () {
    this.page.name = "ahmednadar";
    this.page.title = '<%= @article.headline %>';
    this.page.url = '<%= url_for([@article, {only_path: false}]) %>'; // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @article.id %>';; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  */
  (function() {  // DON'T EDIT BELOW THIS LINE
      var d = document, s = d.createElement('script');

      s.src = '//ahmed-nadar.disqus.com/embed.js';

      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
  })();
%noscript
  Please enable JavaScript to view the
  %a{:href => "https://disqus.com/?ref_noscript", :rel => "nofollow"} comments powered by Disqus.

app/views/articles/_form.html.haml
= simple_form_for @article, html: { class: 'form-horizontal', multipart: true } do |f|
  = f.error :base
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  = f.input :headline, label: false, autofocus: true, required: true, placeholder: "article Headlines *"
  = f.input :intro, label: false, required: true, placeholder: "article Intro *" , input_html: {rows: 5 }, hint: "Used for description META tag, try to keep to under 160 characters."
  = f.input :body, as: :text, label: false,required: true, placeholder: "article Body *", input_html: {rows: 20 }
  = f.error :base
  .actions
    = f.submit 'Save', class: "btn btn-success"
  %br/
  %br/

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
= content_for :page_title, 'All articles'
%article.articles
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        - @articles.each do |article|
          .article-preview
            = link_to article_path(article) do
              %h2.article-title
                = article.headline.capitalize
              %h3.article-subtitle
                = article.intro
            %p.article-meta
              %i.fa.fa-clock-o
              Published on
              %strong= article.created_at.strftime("%m %B %y ")
          %hr

app/views/articles/new.html.haml
= content_for :page_title, 'New Article'
%article.articles
  .container
    .row
      .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
        %h1 New article

        = render 'form'

        = link_to 'Back', articles_path, class: "btn btn-default"
        %br/
        %br/

app/views/articles/show.html.haml
=content_for :page_title, @article.headline.capitalize

%article.article
  .container
    .row
      .col-lg-10.col-lg-offset-2.col-md-10.col-md-offset-1
        %p.notice
          = notice
        %p
          = markdown @article.body
        %hr
        = render 'disqus'

        - if admin_signed_in?  && current_admin
          = link_to  "Edit", edit_article_path(@article), class: "btn btn-info"
          = link_to  "Delete Article", articles_path(@article), method: :delete, data: { confirm: "Are you sure you want to do this?"}, class: "btn btn-danger"
        %hr
        %br/
        %br/

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/partials/head'
  %body
    = render 'layouts/partials/header'
    - flash.each do |name, msg|
      = content_tag(:div, msg, class: "alert alert-info")
    = yield
    = render 'layouts/partials/footer'
    = render 'layouts/partials/contact_modal'
    -# Place JavaScript at the end of the document so the pages load faster
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/articles_layout.html.haml
!!!
%html
  = render 'layouts/partials/head'
  %body
    = render 'layouts/partials/header_articles'

    %header.intro-header
      .container
        .row
          .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
            .site-heading
              %h1 Thinking Outloud
              %hr.small/
              %span.subheading Iterating through a collection of thoughts out loud
    = yield
    = render 'layouts/partials/footer'
    = render 'layouts/partials/contact_modal'
    -# Place JavaScript at the end of the document so the pages load faster
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/partials/_contact_modal.html.haml
/ Modal
#myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"}
        %h4#myModalLabel.modal-title contact us
      .modal-body
        .row.centered
          %p We are available 24/7, so don't hesitate to contact us.
          %p
            Toronto, ON
            %br
            Canada
            %br
            = link_to "Email", 'mailto:ahmednadar@gmail.com', target: "_top"
          #mapwrap
            %iframe{:frameborder => "0", :height => "300", :marginheight => "0", :marginwidth => "0", :scrolling => "no", :src => "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d184551.80843129623!2d-79.51813995434112!3d43.71840386037441!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89d4cb90d7c63ba5%3A0x323555502ab4c477!2sToronto%2C+ON%2C+Canada!5e0!3m2!1sen!2sus!4v1466645058952", :width => "100%", :style => "border:0"}
      .modal-footer
        %button.btn.btn-danger{"data-dismiss" => "modal", :type => "button"} CLose
    / /.modal-content
  / /.modal-dialog
/ /.modal

app/views/layouts/partials/_error_messages.html.haml
- if obj.errors.any?
  .row
    .col-lg-12
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            = pluralize(obj.errors.count, "error")
            prohibited this article from being saved:
          .panel-body
            %ul
              - obj.errors.full_messages.each do |msg|
                %li= msg

app/views/layouts/partials/_footer.html.haml
/ FOOTER
#footer
  .container
    .row.centered
      %a{:href => "http://www.twitter.com/ahmednadar", alt: "Twitter", title: "Twitter", target: "_top" }
        %i.fa.fa-twitter
      %a{:href => "https://plus.google.com/u/0/+AhmedNadar/posts", alt: "Google+", title: "Google+", target: "_top" }
        %i.fa.fa-google-plus
      %a{:href => "http://stackoverflow.com/users/66493/egyamado", alt: "Stack Exchange", title: "Stack Exchange", target: "_top" }
        %i.fa.fa-stack-exchange
      %a{:href => "http://github.com/ahmednadar", alt: "Github", title: "Github", target: "_top" }
        %i.fa.fa-github
      %p.sign
        \&copy; #{Time.now.year} Ahmed Nadar. Made with
        %i.fa.fa-heart
        love in Toronto
    / row
  / container
/ Footer

app/views/layouts/partials/_head.html.haml
%head
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %title= full_title(yield(:page_title))
  %meta{:content => meta_description, :name => "description"}
  %meta{:content => meta_author,      :name => "author"}
  %meta{:content => meta_keywords,    :name => "Keywords"}
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
  %meta{:charset => "utf-8"}
  %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
  %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}
  = render 'layouts/partials/shims'
  = favicon_link_tag 'ahmedsite.ico', type: 'image/ico', sizes: '24x24'
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/layouts/partials/_header.html.haml
/ Fixed navbar
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to site_url, class: "navbar-brand" do
        AHMED NADAR
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        %li{class: active_class('/')}
          = link_to 'HOME', root_path
        %li{class: active_class('/about')}
          = link_to 'ABOUT', about_path
        %li{class: active_class('/services')}
          = link_to 'SERVICES', services_path
        %li{class: active_class('/projects')}
          = link_to 'PROJECTS', projects_path
        %li{class: active_class('')}
          = link_to "#myModal", "data-target" => "#myModal", "data-toggle" => "modal" do
            %i.fa.fa-envelope-o
    / /.nav-collapse

app/views/layouts/partials/_header_articles.html.haml
%nav.navbar.navbar-default.navbar-custom.navbar-fixed-top
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header.page-scroll
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        Menu
        %i.fa.fa-bars
      = link_to site_url, class: "navbar-brand" do
        AHMED NADAR
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li{class: active_class('/')}
          = link_to 'HOME', root_path
        %li{class: active_class('/about')}
          = link_to 'ABOUT', about_path
        %li{class: active_class('/services')}
          = link_to 'SERVICES', services_path
        %li{class: active_class('/projects')}
          = link_to 'PROJECTS', projects_path
        %li{class: active_class('/articles')}
          = link_to 'ARTICLES', articles_path
        %li{class: active_class('')}
          = link_to "#myModal", "data-target" => "#myModal", "data-toggle" => "modal" do
            %i.fa.fa-envelope-o
    / /.navbar-collapse
  / /.container

app/views/layouts/partials/_header_wrap.html.haml
#headerwrap
  .container
    .row.centered
      .col-lg-8.col-lg-offset-2
        %h1
          It Doesn't Take a Rocket
          %b Scientist
        %h2 It Takes a Designer and Developer
    / row
  / container
/ headerwrap

app/views/layouts/partials/_shims.html.haml
/ HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
/[if lt IE 9]
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

app/views/layouts/show_article_layout.html.haml
!!!
%html
  = render 'layouts/partials/head'
  %body
    = render 'layouts/partials/header_articles'
    %header.intro-header
      .container
        .row
          .col-lg-8.col-lg-offset-2.col-md-10.col-md-offset-1
            .site-heading
              %h1
                = @article.headline.capitalize
              %hr.small/
              %span.subheading
                = @article.intro
              %p
                %strong= @article.created_at.strftime("%m %B %Y")
    = yield
    = render 'layouts/partials/footer'
    = render 'layouts/partials/contact_modal'
    -# Place JavaScript at the end of the document so the pages load faster
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/pages/about.html.haml
%article.about
  = content_for :page_title, 'About Us'
  #blue
    .container
      .row.centered
        .col-lg-8.col-lg-offset-2
          %h4 LEARN MORE ABOUT US
      / row
    / container
  / bluewrap


  = render 'pages/partials/about_team'
  = render 'pages/partials/skills'
  = render 'pages/partials/e_story'

app/views/pages/home.html.haml
%article.home
  = content_for :page_title, 'Home'
  = render 'layouts/partials/header_wrap'
  = render 'pages/partials/a_services'
  = render 'pages/partials/b_portfolio'
  = render 'pages/partials/c_feature'
  -# = render 'pages/partials/d_clients'
  = render 'pages/partials/e_story'

app/views/pages/partials/_a_services.html.haml
.container.w
  .row.centered
    %br/
    %br/
    .col-lg-4
      %i.fa.fa-heart
      %h4 WEB DESIGN
      %p All of my designs are high-quality and completely customized to fit my clients needs. I go the extra mile to create unique designs so each time you receive an original final product.
    / col-lg-4
    .col-lg-4
      %i.fa.fa-code
      %h4 DEVELOPMENT
      %p I am always striving hard to learn new technologies, so I’m able to pride myself on having a wide array of programming skills.
    / col-lg-4
    .col-lg-4
      %i.fa.fa-cogs
      %h4 CONSULTING
      %p Finishing your design or setting up your web presence is just the first step. I do SEO and PPC marketing consultations to help my clients maximize their full earning potential!
    / col-lg-4
  / row
  %br/
  %br/
/ container

app/views/pages/partials/_about_team.html.haml
.container.w
  .row.centered
    %br/
    %br/
    .col-lg-8.col-lg-offset-2.col-md-8.col-md-offset-1
      = image_tag asset_path('ahmed_profile.png'), class: "img-circle", alt: "Ahmed Nadar", height: "344", width: "300"
      %h4 Ahmed Nadar
      %p
        Hi. I’m Ahmed Nadar. I’m a Developer and Designer.
        %br
        I’ve been making software for about 10 years now experience on the back-end and front-end using primarily
        %strong Ruby, Ruby on Rails
        and
        %strong Javascript
        in the form of
        %strong Coffeescript.
        %br
        %br
        I help creatives transform their passion into a successful, profitable business.
        %br
        I enjoy turning complex problems into simple, beautiful and intuitive interface designs.
      %p
        = link_to '@ahmedandar', "www.twitter.com/ahmednadar"
  / row
  %br/
  %br/
/ container

app/views/pages/partials/_b_portfolio.html.haml
/ PORTFOLIO SECTION
#dg
  .container
    .row.centered
      %h4 LATEST WORKS
      %br/
      .col-lg-4
        .tilt
          = link_to projects_path do
            = image_tag asset_path('project_1.png'), alt: "Ahmed Nadar"
      .col-lg-4
        .tilt
          = link_to projects_path do
            = image_tag asset_path('project_2.png'), alt: "Ahmed Nadar"
      .col-lg-4
        .tilt
          = link_to projects_path do
            = image_tag asset_path('project_3.png'), alt: "Ahmed Nadar"
    / row
  / container
/ DG

app/views/pages/partials/_c_feature.html.haml
/ FEATURE SECTION
.container.wb
  .row.centered
    %br/
    %br/
    .col-lg-8.col-lg-offset-2
      %h4 WE CREATE FIRST CLASS PRODUCTS
      %p The work I provide is of highest quality, fully responsive, and tested in a wide range of devices. I take great care to ensure each project is well-documented and easily maintainable so you can enhance a website as your company grows.
      %p
        %br/
        %br/
    .col-lg-2
    .col-lg-10.col-lg-offset-1
      = image_tag asset_path('site_feature.png'), class: "img-responsive", alt: "Ahmed Nadar"
  / row
/ container

app/views/pages/partials/_d_clients.html.haml
#lg
  .container
    .row.centered
      %h4 OUR AWESOME CLIENTS
      .col-lg-2.col-lg-offset-1
        = image_tag asset_path('c01.gif'), class: "", alt: "Ahmed Nadar"
      .col-lg-2
        = image_tag asset_path('c02.gif'), class: "", alt: "Ahmed Nadar"
      .col-lg-2
        = image_tag asset_path('c03.gif'), class: "", alt: "Ahmed Nadar"
      .col-lg-2
        = image_tag asset_path('c04.gif'), class: "", alt: "Ahmed Nadar"
      .col-lg-2
        = image_tag asset_path('c05.gif'), class: "", alt: "Ahmed Nadar"
    / row
  / container
/ dg

app/views/pages/partials/_e_story.html.haml
#r
  .container
    .row.centered
      .col-lg-8.col-lg-offset-2
        %h4 WE ARE STORYTELLERS. BRANDS ARE OUR SUBJECTS. DESIGN IS OUR VOICE.
        %p Have an idea, but need someone to implement your vision? I can take your concept, work with you to flesh out the details, write the code and turn your idea into a working site.
        %a{"data-target" => "#myModal", "data-toggle" => "modal", href: "#myModal", class: "btn btn-info center"}
          Get in touch
    / row
  / container
/ r wrap

app/views/pages/partials/_pricing.html.haml
/ PRICING SECTION
#dg
  .container
    .row.centered
      %h4 PRICING PLANS
      %br/
      .col-lg-4
        / START PRICING TABLE
        .pricing-option
          .pricing-top
            %span.pricing-edition Starter
            %span.price
              %sup $
              %span.price-amount 19
              %small /mo
          %ul
            %li
              %strong 10GB
              Storage
            %li
              Up to
              %strong 10
              Users
            %li
              %strong 5
              Domains
            %li
              %strong Free
              Setup
            %li
              %strong 1-year
              Free support *
          %a.pricing-signup{:href => "index.html#"} Sign up
        / /pricing-option
        / END PRICING TABLE
      / /col
      .col-lg-4
        / START PRICING TABLE
        .pricing-option
          .pricing-top
            %span.pricing-edition Standard
            %span.price
              %sup $
              %span.price-amount 29
              %small /mo
          %ul
            %li
              %strong 20GB
              Storage
            %li
              Up to
              %strong 20
              Users
            %li
              %strong 10
              Domains
            %li
              %strong Free
              Setup
            %li
              %strong 2-year
              Free support *
          %a.pricing-signup{:href => "index.html#"} Sign up
        / /pricing-option
        / END PRICING TABLE
      / /col
      .col-lg-4
        / START PRICING TABLE
        .pricing-option
          .pricing-top
            %span.special-label OFFER!
            %span.pricing-edition Ultimate
            %span.price
              %sup $
              %span.price-amount 69
              %small /mo
          %ul
            %li
              %strong 150GB
              Storage
            %li
              %strong Unlimited
              Users
            %li
              %strong 50
              Domains
            %li
              %strong Free
              Setup
            %li
              %strong 5-year
              Free support *
          %a.pricing-signup{:href => "index.html#"} Sign up
        / /pricing-option
        / END PRICING TABLE
      / /col
    / row
  / container
/ DG

app/views/pages/partials/_skills.html.haml
/ PORTFOLIO SECTION
#dg
  .container
    .row.centered
      %h4 SKILLS & MMID SET
      %p I have experience building client projects and personal projects with the most popular languages and frameworks in the industry. There are also some main project guidelines that I like to follow in order to provide the best user and client experiences.
      %br
      / First Chart
      .col-lg-4
        %canvas#canvas{:height => "130", :width => "130"}
        %br
          :javascript
            var doughnutData = [
            		{
            			value: 70,
            			color:"#3498db"
            		},
            		{
            			value : 30,
            			color : "#ecf0f1"
            		}
            	];
            	var myDoughnut = new Chart(document.getElementById("canvas").getContext("2d")).Doughnut(doughnutData);
          %p
            %b Design  Brand
          %p
            %small Websites should allow their users to accomplish their goals in a pleasant and efficient way.
        / /col-lg-3
        / Second Chart
      .col-lg-4
        %canvas#canvas2{:height => "130", :width => "130"}
        %br
          :javascript
            var doughnutData = [
            		{
            			value: 90,
            			color:"#3498db"
            		},
            		{
            			value : 10,
            			color : "#ecf0f1"
            		}
            	];
            	var myDoughnut = new Chart(document.getElementById("canvas2").getContext("2d")).Doughnut(doughnutData);
          %p
            %b Web Development
          %p
            %small With users visiting websites from devices of all sizes, a website must be optimized across all devices.
        / /col-lg-3
        / Third Chart
      .col-lg-4
        %canvas#canvas3{:height => "130", :width => "130"}
        %br
          :javascript
            var doughnutData = [
            		{
            			value: 80,
            			color:"#3498db"
            		},
            		{
            			value : 20,
            			color : "#ecf0f1"
            		}
            	];
            	var myDoughnut = new Chart(document.getElementById("canvas3").getContext("2d")).Doughnut(doughnutData);
          %p
            %b Modern Browser Compatible
          %p
            %small A website should provide the same experience and be compatible across all modern browsers.
      / /col-lg-3
      / third Chart
    / row
  / container
/ DG